import { isEqual } from "lodash";
import dynamic from "next/dynamic";
import { memo } from "react";
const GridMoviePoster = dynamic(() => import("./GridMoviePoster"));
const Pagination = dynamic(() => import("./Pagination"));


function GridMovie() {
  const Movie = [
    {
      adult: false,
      backdrop_path: "/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg",
      genre_ids: [16, 28, 12, 14],
      id: 635302,
      original_language: "ja",
      original_title: "劇場版「鬼滅の刃」無限列車編",
      overview:
        "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      popularity: 677.1,
      poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
      release_date: "2020-10-16",
      title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
      video: false,
      vote_average: 8.4,
      vote_count: 1655,
    },
    {
      adult: false,
      backdrop_path: "/owraiceOKtSOa3t8sp3wA9K2Ox6.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 703771,
      original_language: "en",
      original_title: "Deathstroke: Knights & Dragons - The Movie",
      overview:
        "The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.",
      popularity: 458.312,
      poster_path: "/vFIHbiy55smzi50RmF8LQjmpGcx.jpg",
      release_date: "2020-08-04",
      title: "Deathstroke: Knights & Dragons - The Movie",
      video: false,
      vote_average: 7,
      vote_count: 229,
    },
    {
      adult: false,
      backdrop_path: "/z2UtGA1WggESspi6KOXeo66lvLx.jpg",
      genre_ids: [878, 53, 27],
      id: 520763,
      original_language: "en",
      original_title: "A Quiet Place Part II",
      overview:
        "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
      popularity: 435.4,
      poster_path: "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
      release_date: "2021-05-21",
      title: "A Quiet Place Part II",
      video: false,
      vote_average: 7.7,
      vote_count: 2974,
    },
    {
      adult: false,
      backdrop_path: "/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg",
      genre_ids: [28, 12, 53],
      id: 581387,
      original_language: "ko",
      original_title: "백두산",
      overview:
        "A group of unlikely heroes from across the Korean peninsula try to save the day after a volcano erupts on the mythical and majestic Baekdu Mountain.",
      popularity: 419.524,
      poster_path: "/gCZ0RHifBxZGedde7WPWSgjpyZt.jpg",
      release_date: "2019-12-19",
      title: "Ashfall",
      video: false,
      vote_average: 6.4,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg",
      genre_ids: [80, 53],
      id: 637534,
      original_language: "fr",
      original_title: "BAC Nord",
      overview:
        "A police brigade working in the dangerous northern neighborhoods of Marseille, where the level of crime is higher than anywhere else in France.",
      popularity: 381.142,
      poster_path: "/nRGP7gA72PzNo6OYigBf8v2BIc.jpg",
      release_date: "2021-08-18",
      title: "The Stronghold",
      video: false,
      vote_average: 8,
      vote_count: 266,
    },
    {
      adult: false,
      backdrop_path: "/6hgItrYQEG33y0I7yP2SRl2ei4w.jpg",
      genre_ids: [10749, 18],
      id: 613504,
      original_language: "en",
      original_title: "After We Collided",
      overview:
        "Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.",
      popularity: 336.596,
      poster_path: "/kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg",
      release_date: "2020-09-02",
      title: "After We Collided",
      video: false,
      vote_average: 7.3,
      vote_count: 4144,
    },
    {
      adult: false,
      backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
      genre_ids: [28, 12, 14],
      id: 464052,
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
      popularity: 314.811,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Wonder Woman 1984",
      video: false,
      vote_average: 6.7,
      vote_count: 5903,
    },
    {
      adult: false,
      backdrop_path: "/fmIp40ev4VGquK2bMo52PQgaV2d.jpg",
      genre_ids: [16, 10751, 12, 14, 35],
      id: 529203,
      original_language: "en",
      original_title: "The Croods: A New Age",
      overview:
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
      popularity: 296.431,
      poster_path: "/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg",
      release_date: "2020-11-25",
      title: "The Croods: A New Age",
      video: false,
      vote_average: 7.6,
      vote_count: 2539,
    },
    {
      adult: false,
      backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      genre_ids: [80, 53, 18],
      id: 475557,
      original_language: "en",
      original_title: "Joker",
      overview:
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      popularity: 303.949,
      poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      release_date: "2019-10-02",
      title: "Joker",
      video: false,
      vote_average: 8.2,
      vote_count: 18637,
    },
    {
      adult: false,
      backdrop_path: "/9guoVF7zayiiUq5ulKQpt375VIy.jpg",
      genre_ids: [16, 28, 14, 12],
      id: 592350,
      original_language: "ja",
      original_title: "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
      overview:
        "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
      popularity: 278.84,
      poster_path: "/zGVbrulkupqpbwgiNedkJPyQum4.jpg",
      release_date: "2019-12-20",
      title: "My Hero Academia: Heroes Rising",
      video: false,
      vote_average: 8.5,
      vote_count: 796,
    },
    {
      adult: false,
      backdrop_path: "/qMxpGzmmnY1jLd4p7EhhoW43wWF.jpg",
      genre_ids: [16, 14, 10751],
      id: 683127,
      original_language: "ja",
      original_title: "アーヤと魔女",
      overview:
        "A headstrong orphan discovers a world of spells and potions while living with a selfish witch.",
      popularity: 311.975,
      poster_path: "/86jyzdxtAX8p956rVQDKwGbrYh2.jpg",
      release_date: "2021-01-27",
      title: "Earwig and the Witch",
      video: false,
      vote_average: 6.2,
      vote_count: 63,
    },
    {
      adult: false,
      backdrop_path: "/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg",
      genre_ids: [27, 53, 12, 9648],
      id: 522444,
      original_language: "en",
      original_title: "Black Water: Abyss",
      overview:
        "An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.",
      popularity: 289.615,
      poster_path: "/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg",
      release_date: "2020-07-09",
      title: "Black Water: Abyss",
      video: false,
      vote_average: 5.1,
      vote_count: 270,
    },
    {
      adult: false,
      backdrop_path: "/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg",
      genre_ids: [28, 80],
      id: 495764,
      original_language: "en",
      original_title:
        "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
      overview:
        "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
      popularity: 265.559,
      poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
      release_date: "2020-02-05",
      title:
        "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
      video: false,
      vote_average: 7.1,
      vote_count: 8068,
    },
    {
      adult: false,
      backdrop_path: "/aMFl4wOPhJ7NVua6SgU9zIJvFSx.jpg",
      genre_ids: [16, 10751, 35, 12, 10770],
      id: 755812,
      original_language: "fr",
      original_title: "Miraculous World : New York, les héros unis",
      overview:
        "During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.",
      popularity: 285.942,
      poster_path: "/19kfvGktytDZInUmpv3WlaHoTxP.jpg",
      release_date: "2020-09-26",
      title: "Miraculous World: New York, United HeroeZ",
      video: false,
      vote_average: 8.3,
      vote_count: 793,
    },
    {
      adult: false,
      backdrop_path: "/z8TvnEVRenMSTemxYZwLGqFofgF.jpg",
      genre_ids: [28, 14, 12],
      id: 458576,
      original_language: "en",
      original_title: "Monster Hunter",
      overview:
        "A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
      popularity: 264.702,
      poster_path: "/1UCOF11QCw8kcqvce8LKOO6pimh.jpg",
      release_date: "2020-12-03",
      title: "Monster Hunter",
      video: false,
      vote_average: 6.9,
      vote_count: 2117,
    },
    {
      adult: false,
      backdrop_path: "/g9fS7s8V54wyFRc2O9iAowPJCNB.jpg",
      genre_ids: [16, 35, 10751],
      id: 778814,
      original_language: "en",
      original_title: "Daisy Quokka: World's Scariest Animal",
      overview:
        "When an unbearably adorable, eternally optimistic Quokka named Daisy wants to achieve the impossible – to win the annual ‘World’s Scariest Animal’ championship, she enlists the guidance of a washed-up, former champion, a grouchy Saltwater Crocodile, to help her achieve her dreams and prove that champions can come in all sizes.",
      popularity: 228.96,
      poster_path: "/jjV1DY1SlGI1eUJAXSdre8bpw7t.jpg",
      release_date: "2021-02-04",
      title: "Daisy Quokka: World's Scariest Animal",
      video: false,
      vote_average: 7,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: "/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg",
      genre_ids: [28, 12, 80],
      id: 604822,
      original_language: "zh",
      original_title: "急先锋",
      overview:
        "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
      popularity: 234.518,
      poster_path: "/mKvw1Ic9enfFlCPBNJGiejRPMUO.jpg",
      release_date: "2020-09-30",
      title: "Vanguard",
      video: false,
      vote_average: 6.3,
      vote_count: 360,
    },
    {
      adult: false,
      backdrop_path: "/pU15NMZueYMpcnJmBSB63a8uIMV.jpg",
      genre_ids: [53, 878],
      id: 687149,
      original_language: "es",
      original_title: "Tóxico",
      overview:
        "In the middle of a mysterious insomnia epidemic that slowly takes on catastrophic dimensions, Laura (39) and Augusto (42) flee the city in their motorhome to get away from the chaos. As they move down the route, the world becomes an increasingly strange and dangerous place. Finally, Laura reveals a story that changes everything. The road is depopulating, the silence grows and it is increasingly difficult to differentiate the reality from the dream.",
      popularity: 210.964,
      poster_path: "/mWL4lyP4DhEkg73rjUoALXguIXh.jpg",
      release_date: "2020-04-23",
      title: "Toxic",
      video: false,
      vote_average: 7,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/3N316jUSdhvPyYTW29G4v9ebbcS.jpg",
      genre_ids: [53, 28, 80],
      id: 38700,
      original_language: "en",
      original_title: "Bad Boys for Life",
      overview:
        "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
      popularity: 236.511,
      poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
      release_date: "2020-01-15",
      title: "Bad Boys for Life",
      video: false,
      vote_average: 7.2,
      vote_count: 6535,
    },
    {
      adult: false,
      backdrop_path: "/54yOImQgj8i85u9hxxnaIQBRUuo.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 539885,
      original_language: "en",
      original_title: "Ava",
      overview:
        "A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.",
      popularity: 232.417,
      poster_path: "/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg",
      release_date: "2020-07-02",
      title: "Ava",
      video: false,
      vote_average: 5.7,
      vote_count: 1723,
    },
  ];
  // =====    =====    =====    =====    =====    =====    function

  // =====    =====    =====    =====    =====    =====    effect
  return (
    <div className="p-4 container mx-auto">
      <ul className="grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 ">
        {Movie.map((oneMovie) => (
          <li
            key={oneMovie.id}
            className="h-[65vh] sm:h-[75vh] md:h-96 border-4 border-opacity-20 overflow-hidden rounded"
          >
            <GridMoviePoster movie={oneMovie} />
          </li>
        ))}
      </ul>
      <Pagination />
    </div>
  );
}
export default memo(GridMovie, isEqual);
