// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json({
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/gzppdxEJ6fofhtLzSVSUJZEVxvq.jpg",
        genre_ids: [28, 878, 53],
        id: 848278,
        original_language: "en",
        original_title: "Jurassic Hunt",
        overview:
          "Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!",
        popularity: 3499.182,
        poster_path: "/bZnOioDq1ldaxKfUoj3DenHU7mp.jpg",
        release_date: "2021-09-01",
        title: "Jurassic Hunt",
        video: false,
        vote_average: 4.7,
        vote_count: 73,
      },
      {
        adult: false,
        backdrop_path: "/xDnFlNrNUoSKPq4uptnhYmUZNpm.jpg",
        genre_ids: [27, 53, 9648, 28, 80],
        id: 619778,
        original_language: "en",
        original_title: "Malignant",
        overview:
          "Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities.",
        popularity: 2451.161,
        poster_path: "/dGv2BWjzwAz6LB8a8JeRIZL8hSz.jpg",
        release_date: "2021-09-01",
        title: "Malignant",
        video: false,
        vote_average: 7.4,
        vote_count: 353,
      },
      {
        adult: false,
        backdrop_path: "/nDLylQOoIazGyYuWhk21Yww5FCb.jpg",
        genre_ids: [28, 12, 14],
        id: 566525,
        original_language: "en",
        original_title: "Shang-Chi and the Legend of the Ten Rings",
        overview:
          "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        popularity: 2364.887,
        poster_path: "/xeItgLK9qcafxbd8kYgv7XnMEog.jpg",
        release_date: "2021-09-01",
        title: "Shang-Chi and the Legend of the Ten Rings",
        video: false,
        vote_average: 7.9,
        vote_count: 797,
      },
      {
        adult: false,
        backdrop_path: "/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
        genre_ids: [28, 878, 12],
        id: 588228,
        original_language: "en",
        original_title: "The Tomorrow War",
        overview:
          "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",
        popularity: 1860.087,
        poster_path: "/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
        release_date: "2021-09-03",
        title: "The Tomorrow War",
        video: false,
        vote_average: 7.6,
        vote_count: 422,
      },
      {
        adult: false,
        backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
        genre_ids: [28, 12, 14, 35],
        id: 436969,
        original_language: "en",
        original_title: "The Suicide Squad",
        overview:
          "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        popularity: 2145.26,
        poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
        release_date: "2021-07-28",
        title: "The Suicide Squad",
        video: false,
        vote_average: 7.9,
        vote_count: 3796,
      },
      {
        adult: false,
        backdrop_path: "/vD8oPUpDUZDTGI5IVofxrUjxxUO.jpg",
        genre_ids: [28, 53],
        id: 595743,
        original_language: "en",
        original_title: "SAS: Red Notice",
        overview:
          "An off-duty SAS soldier, Tom Buckingham, must thwart a terror attack on a train running through the Channel Tunnel. As the action escalates on the train, events transpire in the corridors of power that may make the difference as to whether Buckingham and the civilian passengers make it out of the tunnel alive.",
        popularity: 1726.56,
        poster_path: "/6Y9fl8tD1xtyUrOHV2MkCYTpzgi.jpg",
        release_date: "2021-08-11",
        title: "SAS: Red Notice",
        video: false,
        vote_average: 5.9,
        vote_count: 144,
      },
      {
        adult: false,
        backdrop_path: "/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg",
        genre_ids: [53, 27],
        id: 482373,
        original_language: "en",
        original_title: "Don't Breathe 2",
        overview:
          "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.",
        popularity: 1474.822,
        poster_path: "/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg",
        release_date: "2021-08-12",
        title: "Don't Breathe 2",
        video: false,
        vote_average: 7.7,
        vote_count: 538,
      },
      {
        adult: false,
        backdrop_path: "/fQB7APBjtBKpOakeDi9sUXbBeCR.jpg",
        genre_ids: [27, 53, 9648, 28, 878],
        id: 585216,
        original_language: "en",
        original_title: "Escape Room: Tournament of Champions",
        overview:
          "Six people unwittingly find themselves locked in another series of escape rooms, slowly uncovering what they have in common to survive as they discover all the games that they've played before.",
        popularity: 1805.192,
        poster_path: "/jGYJyPzVgrVV2bgClI9uvEZgVLE.jpg",
        release_date: "2021-07-01",
        title: "Escape Room: Tournament of Champions",
        video: false,
        vote_average: 7.1,
        vote_count: 281,
      },
      {
        adult: false,
        backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
        genre_ids: [12, 14, 35, 28],
        id: 451048,
        original_language: "en",
        original_title: "Jungle Cruise",
        overview:
          "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
        popularity: 1458.818,
        poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
        release_date: "2021-07-28",
        title: "Jungle Cruise",
        video: false,
        vote_average: 7.9,
        vote_count: 2570,
      },
      {
        adult: false,
        backdrop_path: "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
        genre_ids: [28, 12, 53, 878],
        id: 497698,
        original_language: "en",
        original_title: "Black Widow",
        overview:
          "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
        popularity: 1392.609,
        poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
        release_date: "2021-07-07",
        title: "Black Widow",
        video: false,
        vote_average: 7.8,
        vote_count: 4972,
      },
      {
        adult: false,
        backdrop_path: "/mtRW6eAwOO27h3zrfU2foQFW7Hg.jpg",
        genre_ids: [16, 10751, 12, 35],
        id: 675445,
        original_language: "en",
        original_title: "PAW Patrol: The Movie",
        overview:
          "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.",
        popularity: 1289.238,
        poster_path: "/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
        release_date: "2021-08-09",
        title: "PAW Patrol: The Movie",
        video: false,
        vote_average: 8,
        vote_count: 404,
      },
      {
        adult: false,
        backdrop_path: "/nprqOIEfiMMQx16lgKeLf3rmPrR.jpg",
        genre_ids: [28],
        id: 619297,
        original_language: "en",
        original_title: "Sweet Girl",
        overview:
          "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
        popularity: 1259.71,
        poster_path: "/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
        release_date: "2021-08-18",
        title: "Sweet Girl",
        video: false,
        vote_average: 6.9,
        vote_count: 528,
      },
      {
        adult: false,
        backdrop_path: "/849RDhbADVVnhtggR14dDBYejeN.jpg",
        genre_ids: [14, 10749, 35],
        id: 593910,
        original_language: "en",
        original_title: "Cinderella",
        overview:
          "Cinderella, an orphaned girl with an evil stepmother, has big dreams and with the help of her Fabulous Godmother, she perseveres to make them come true.",
        popularity: 1085.945,
        poster_path: "/clDFqATL4zcE7LzUwkrVj3zHvk7.jpg",
        release_date: "2021-09-03",
        title: "Cinderella",
        video: false,
        vote_average: 6.8,
        vote_count: 558,
      },
      {
        adult: false,
        backdrop_path: "/8s4h9friP6Ci3adRGahHARVd76E.jpg",
        genre_ids: [16, 35, 10751, 878],
        id: 379686,
        original_language: "en",
        original_title: "Space Jam: A New Legacy",
        overview:
          "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
        popularity: 1097.894,
        poster_path: "/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
        release_date: "2021-07-08",
        title: "Space Jam: A New Legacy",
        video: false,
        vote_average: 7.4,
        vote_count: 2163,
      },
      {
        adult: false,
        backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
        genre_ids: [878, 28, 53],
        id: 581726,
        original_language: "en",
        original_title: "Infinite",
        overview:
          "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
        popularity: 1114.778,
        poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
        release_date: "2021-06-10",
        title: "Infinite",
        video: false,
        vote_average: 7.5,
        vote_count: 1029,
      },
      {
        adult: false,
        backdrop_path: "/dssCw0mUmD4EriUmkwB3PnsGu4q.jpg",
        genre_ids: [16, 28, 14],
        id: 841755,
        original_language: "en",
        original_title: "Mortal Kombat Legends: Battle of the Realms",
        overview:
          "The Earthrealm heroes must journey to the Outworld and fight for the survival of their homeland, invaded by the forces of evil warlord Shao Kahn, in the tournament to end all tournaments: the final Mortal Kombat.",
        popularity: 946.878,
        poster_path: "/ablrE8IbWcIrAxMmm4gnPn75AMS.jpg",
        release_date: "2021-08-30",
        title: "Mortal Kombat Legends: Battle of the Realms",
        video: false,
        vote_average: 8.1,
        vote_count: 102,
      },
      {
        adult: false,
        backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
        genre_ids: [16, 35, 10751, 14],
        id: 508943,
        original_language: "en",
        original_title: "Luca",
        overview:
          "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
        popularity: 1046.376,
        poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
        release_date: "2021-06-17",
        title: "Luca",
        video: false,
        vote_average: 8.1,
        vote_count: 4456,
      },
      {
        adult: false,
        backdrop_path: "/1Txzm4bY5ZDqvgMl7MmHeBMl7HH.jpg",
        genre_ids: [80, 18, 53],
        id: 860425,
        original_language: "es",
        original_title: "Sinaliento",
        overview:
          "In the DR, hardened cop Manolo tries to take down an infamous drug cartel; meanwhile, his daughter has fallen in love with Lorenzo, a construction worker who's unwittingly gotten embroiled in the drug cartel's dealings.",
        popularity: 1011.388,
        poster_path: "/oxNoVgbu2v9ETL93Kri1pw8osYf.jpg",
        release_date: "2021-08-11",
        title: "Breathless",
        video: false,
        vote_average: 6.4,
        vote_count: 24,
      },
      {
        adult: false,
        backdrop_path: "/z1s7yuQbDOhJE2zvvADofBCL9j1.jpg",
        genre_ids: [16, 35, 12, 10751],
        id: 459151,
        original_language: "en",
        original_title: "The Boss Baby: Family Business",
        overview:
          "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
        popularity: 1047.785,
        poster_path: "/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
        release_date: "2021-07-01",
        title: "The Boss Baby: Family Business",
        video: false,
        vote_average: 7.8,
        vote_count: 1365,
      },
      {
        adult: false,
        backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
        genre_ids: [28, 80, 53],
        id: 385128,
        original_language: "en",
        original_title: "F9",
        overview:
          "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
        popularity: 1001.717,
        poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
        release_date: "2021-05-19",
        title: "F9",
        video: false,
        vote_average: 7.5,
        vote_count: 3610,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  });
}
